export const copy = {
  brand: "MetaAgent Studio",
  tagline: "Turn an idea into a working helper",
  statusReady: "Ready",
  statusThinking: "Thinking…",
  nav: {
    home: "Start",
    studio: "Build my agent",
    check: "Make sure it works",
    improve: "Make it better",
    kits: "My saved kits",
    connections: "Connections",
    settings: "Settings",
  },
  connections: {
    title: "Connections",
    support: "Plug in apps and tool servers your helper can use.",
    tabApps: "Apps & tools",
    tabMcp: "MCP servers",
    appsBlurb: "Connect everyday apps. Secrets stay on this computer.",
    mcpBlurb:
      "MCP servers give your helper extra tools. Advanced — leave off if you’re unsure.",
    connected: "Connected",
    notConnected: "Not connected",
    connect: "Connect",
    disconnect: "Disconnect",
    test: "Test",
    testing: "Testing…",
    addApp: "Add custom app",
    addMcp: "Add MCP server",
    name: "Name",
    baseUrl: "Base URL",
    command: "Command",
    args: "Args (space-separated)",
    transport: "How it runs",
    transportStdio: "Local command",
    transportSse: "SSE URL",
    transportHttp: "HTTP URL",
    enabled: "On",
    disabled: "Off",
    turnOn: "Turn on",
    turnOff: "Turn off",
    save: "Save",
    remove: "Remove",
    emptyMcp: "No MCP servers yet — add one below if you need extra tools.",
    testOk: "Looks good",
    testFail: "Couldn’t reach it — check the details",
  },
  home: {
    support: "Describe what you want. We’ll guide the rest.",
    placeholder: "Example: Sort support emails and draft kind replies…",
    cta: "Start building",
    examples: [
      "Help with support emails",
      "Read invoices safely",
      "Summarize research notes",
    ],
  },
  studio: {
    steps: [
      "Your idea",
      "A few questions",
      "Approve the plan",
      "Who does what",
      "Build the kit",
    ],
    next: "Continue",
    back: "Back",
    approve: "Looks good",
    paths: {
      happy: "Smooth day",
      ambiguity: "Missing pieces",
      failure: "When things break",
    },
    tiers: {
      t1: "Rules",
      t2: "Smart match",
      t3: "AI writer",
    },
    buildCta: "Build kit & check",
  },
  check: {
    title: "Make sure it works",
    empty: "Build a kit first from Build my agent.",
    score: "Overall score",
    packageOk: "Files written",
    testsOk: "Checks ran",
    zipOk: "Zip ready",
    improve: "Make it better",
    save: "Save kit",
  },
  improve: {
    title: "Make it better",
    edges: "Tricky situations",
    prompts: "Ask a coding helper",
    copyPrompt: "Copy prompt",
    iterate: "Try another improvement",
  },
  kits: {
    title: "My saved kits",
    empty: "No kits yet — build one from Start.",
    fork: "Reuse",
    open: "Open",
  },
  settings: {
    title: "Settings",
    license: "License key",
    activate: "Activate",
    brain: "Brain",
    local: "Local",
    cloud: "Cloud",
    export: "Save finished kits to",
    developer: "Developer",
    greet: "Test Rust bridge",
    activity: "Activity log",
    activityEmpty: "Nothing logged yet — actions will show up here.",
    activityClear: "Clear log",
    activitySupport: "Recent actions on this computer. Kept after refresh.",
  },
  pathsAscii: {
    happy: "Check input → Find notes → Write reply → Send safely",
    ambiguity: "Check input → Ask what’s missing → Wait",
    failure: "Check input → Service busy → Queue & retry",
  },
} as const;

export type ViewId =
  | "home"
  | "studio"
  | "check"
  | "improve"
  | "kits"
  | "connections"
  | "settings";
